services:
  gateway:
    build: ./gateway
    container_name: techreviews-gateway
    depends_on:
      - auth-service
      - product-service
    environment:
      - PORT=8080
      - AUTH_SERVICE_URL=http://auth-service:4001
      - PRODUCT_SERVICE_URL=http://product-service:4002
      - JWT_ACCESS_SECRET=dev_access_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
    ports:
      - "8080:8080"

  auth-service:
    build: ./auth-service
    container_name: techreviews-auth
    environment:
      - PORT=4001
      - DATABASE_URL=postgres://auth_user:auth_password@auth-db:5432/auth_db
      - JWT_ACCESS_SECRET=dev_access_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
      - BCRYPT_SALT_ROUNDS=10
    depends_on:
      - auth-db

  product-service:
    build: ./product-service
    container_name: techreviews-product
    environment:
      - PORT=4002
      - DATABASE_URL=postgres://product_user:product_password@product-db:5432/product_db
    depends_on:
      - product-db
    volumes:
      - ./uploads:/usr/src/app/uploads

  auth-db:
    image: postgres:16
    container_name: techreviews-auth-db
    environment:
      - POSTGRES_DB=auth_db
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_password
    ports:
      - "5433:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  product-db:
    image: postgres:16
    container_name: techreviews-product-db
    environment:
      - POSTGRES_DB=product_db
      - POSTGRES_USER=product_user
      - POSTGRES_PASSWORD=product_password
    ports:
      - "5434:5432"
    volumes:
      - product-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
  product-db-data:

